### ISSUE TITLE
Convert from SCM-Plugin to AWS-Plugin

### ISSUE THREAD

**Issue by nickgrealy** [nickgrealy/aws-sqs#1]
## Done
- [x] Remove dependency on GitHub specific Events
- [x] Remove "required" validation on "AccessKey" and "SecretKey" fields (can be implicit role on machine)
- [x] Rename packages to avoid conflicts with SCM configuration
- [x] REBRAND: from `scm-sqs` to `aws-sqs`
## Todo
- [ ] Clean up redundant classes from SCM plugin
- [ ] Update documentation
## Longer Term
- [ ] Use EnvironmentContributor (to workaround SECURITY-170)
- [ ] Migrate to gradle
- [ ] Review unit tests
